name: matrix_link_text
description: Easy to use text widget for Flutter apps, which converts inlined urls into working, clickable links. Allows for custom styling. Supports matrix identifiers
version: 1.1.0
repository: https://gitlab.com/famedly/company/frontend/libraries/matrix_link_text.git
homepage: https://gitlab.com/famedly/company/frontend/libraries/matrix_link_text

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.4
  punycode: ^1.0.0
  flutter_lints: any
